#ifndef GPT_CFG_H
#define GPT_CFG_H

#define GPT_CFG_CONFIGURED_CHANNELS 	1
#define GPT_CFG_TIMER_STATE						GPT_INDIVIDUAL
#define GPT_CFG_INTERRUPT							GPT_INTERRUPT_ENABLE
#define GPT_CFG_COUNT_DIRECTION				GPT_TIMER_COUNT_DOWN
#define GPT_PREDEF_TIMER_1US_16BIT 		GPT_ENABLE
#define GPT_PREDEF_TIMER_1US_24BIT 		GPT_ENABLE
#define GPT_PREDEF_TIMER_1US_32BIT 		GPT_ENABLE
#define GPT_PREDEF_TIMER_100US_16BIT	GPT_ENABLE
#define GPT_CFG_SNAPSHOT							GPT_SNAPSHOT_DISABLE

#endif